[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask-sqlalchemy>=3.1.1",
    "flask>=3.1.0",
    "pillow>=11.2.1",
    "werkzeug>=3.1.3",
    "reportlab>=4.3.1",
    "pytz>=2025.2",
]
